site_name: Bitflow
theme: readthedocs
nav:
    - Home: index.md
    - Data Sources, Sinks and Protocol: data_format.md
    - Bitflow Script: script.md
    - Implementations:
        - go-bitflow: "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
        - bitflow4j (Github): "https://github.com/bitflow-stream/bitflow4j"
        - python-bitflow: "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
    - Related Projects:
        - bitflow-collector: "https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/"
        - bitflow-antlr-grammars (Github): "https://github.com/bitflow-stream/antlr-grammars"
        - bitflow-coordinator (Github): "https://github.com/bitflow-stream/bitflow-coordinator"
        - bitflow-process-agent (Github): "https://github.com/bitflow-stream/bitflow-process-agent"

