site_name: Bitflow
repo_url: https://github.com/bitflow-stream/bitflow-docs
site_author: The Bitflow Team
site_description: Bitflow Documentation
theme: readthedocs
plugins:
    - search
markdown_extensions:
    - sane_lists
    - smarty
    - toc:
        permalink: True
nav:
    - Home:
        - The Bitflow Project: index.md
        - Data Sources, Sinks and Format: data_format.md
        - Bitflow Script: "https://bitflow.readthedocs.io/projects/antlr-grammars/en/latest/bitflow-script"
    - Implementations:
        - go-bitflow: "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
        - bitflow4j (Github): "https://github.com/bitflow-stream/bitflow4j"
        - python-bitflow: "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
    - Related Projects:
        - bitflow-collector: "https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/"
        - bitflow-antlr-grammars (Github): "https://github.com/bitflow-stream/antlr-grammars"
        - bitflow-coordinator (Github): "https://github.com/bitflow-stream/bitflow-coordinator"
        - bitflow-process-agent (Github): "https://github.com/bitflow-stream/bitflow-process-agent"

