site_name: Bitflow Documentation
repo_url: https://github.com/bitflow-stream/bitflow-docs
theme: readthedocs
plugins: [ search ]
nav:
- Home: index.md
- General:
  - "Sources, Sinks and the Data Format": data_format.md
  - "Bitflow Script": script.md
- Implementations:
  - "go-bitflow": "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
  - "bitflow4j": "https://bitflow.readthedocs.io/projects/bitflow4j/en/latest/"
  - "python-bitflow": "https://bitflow.readthedocs.io/projects/python-bitflow/en/latest/"
- Related Projects:
  - "bitflow-collector": "https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/"

